// FILE: lib/services/export_import_service.dart
import 'dart:io';
import 'dart:convert';
import 'dart:math';
import 'package:archive/archive.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:file_picker/file_picker.dart';
import 'package:event_countdown/database_helper.dart';
import 'package:event_countdown/models/event.dart';

// ==================== CONSTANTS ====================
const String _kAppName = 'Event Countdown';
const String _kAppVersion = '1.0.0';
const int _kExportVersion = 2;

// ==================== HELPER CLASSES ====================
class ExportResult {
  final bool success;
  final String? filePath;
  final int? eventCount;
  final int? totalTableCount;
  final int? fileSizeBytes;
  final DateTime? exportedAt;
  final String? exportType;
  final String? checksum;
  final String? errorMessage;

  const ExportResult({
    required this.success,
    this.filePath,
    this.eventCount,
    this.totalTableCount,
    this.fileSizeBytes,
    this.exportedAt,
    this.exportType,
    this.checksum,
    this.errorMessage,
  });

  String get fileSizeReadable {
    final bytes = fileSizeBytes;
    if (bytes == null || bytes <= 0) return '0 B';
    const suffixes = ['B', 'KB', 'MB', 'GB', 'TB'];
    final i = (log(bytes.toDouble()) / log(1024)).floor().clamp(0, suffixes.length - 1);
    final size = bytes / pow(1024, i);
    return '${size.toStringAsFixed(i == 0 ? 0 : 1)} ${suffixes[i]}';
  }
}

class ImportPreview {
  final String exportType;
  final String appVersion;
  final DateTime? exportedAt;
  final Map<String, int> tableRowCounts;
  final int totalRows;
  final String? checksum;
  final bool checksumValid;
  final List<String> warnings;

  const ImportPreview({
    required this.exportType,
    required this.appVersion,
    this.exportedAt,
    required this.tableRowCounts,
    required this.totalRows,
    this.checksum,
    required this.checksumValid,
    required this.warnings,
  });
}

class _CsvHelper {
  static String encode(List<List<String>> rows) {
    final buffer = StringBuffer();
    for (final row in rows) {
      final escaped = row.map((field) {
        if (field.contains(',') || field.contains('"') || field.contains('\n')) {
          final escapedField = field.replaceAll('"', '""');
          return '"$escapedField"';
        }
        return field;
      }).join(',');
      buffer.writeln(escaped);
    }
    return buffer.toString();
  }

  static List<List<String>> decode(String csv) {
    final rows = <List<String>>[];
    final lines = csv.split('\n');
    for (var line in lines) {
      line = line.trim();
      if (line.isEmpty) continue;
      final fields = <String>[];
      var current = StringBuffer();
      var inQuotes = false;
      for (var i = 0; i < line.length; i++) {
        final char = line[i];
        if (char == '"') {
          if (inQuotes && i + 1 < line.length && line[i + 1] == '"') {
            current.write('"');
            i++; // skip next quote
          } else {
            inQuotes = !inQuotes;
          }
        } else if (char == ',' && !inQuotes) {
          fields.add(current.toString());
          current = StringBuffer();
        } else {
          current.write(char);
        }
      }
      fields.add(current.toString());
      rows.add(fields);
    }
    return rows;
  }
}

// ==================== MODEL CLASSES ====================
class AttendanceRecord {
  final int? id;
  final String subjectName;
  final int? subjectId;
  final int? scheduleId;
  final int dateMillis;
  final String status;
  final String? note;
  final int? markedAtMillis;
  final int isAutoGenerated;
  final int createdAtMillis;

  const AttendanceRecord({
    this.id,
    required this.subjectName,
    this.subjectId,
    this.scheduleId,
    required this.dateMillis,
    required this.status,
    this.note,
    this.markedAtMillis,
    this.isAutoGenerated = 0,
    required this.createdAtMillis,
  });

  static List<String> get csvHeaders => [
        'id',
        'subjectName',
        'subjectId',
        'scheduleId',
        'dateMillis',
        'status',
        'note',
        'markedAtMillis',
        'isAutoGenerated',
        'createdAtMillis',
      ];

  List<String> toCsvRow() => [
        id?.toString() ?? '',
        subjectName,
        subjectId?.toString() ?? '',
        scheduleId?.toString() ?? '',
        dateMillis.toString(),
        status,
        note ?? '',
        markedAtMillis?.toString() ?? '',
        isAutoGenerated.toString(),
        createdAtMillis.toString(),
      ];

  factory AttendanceRecord.fromCsvRow(List<String> row) {
    if (row.length < 6) {
      throw FormatException('AttendanceRecord CSV row must have at least 6 columns, got ${row.length}');
    }
    return AttendanceRecord(
      id: row[0].isNotEmpty ? int.parse(row[0]) : null,
      subjectName: row[1],
      subjectId: row[2].isNotEmpty ? int.parse(row[2]) : null,
      scheduleId: row[3].isNotEmpty ? int.parse(row[3]) : null,
      dateMillis: int.parse(row[4]),
      status: row[5],
      note: row.length > 6 ? (row[6].isNotEmpty ? row[6] : null) : null,
      markedAtMillis: row.length > 7 && row[7].isNotEmpty ? int.parse(row[7]) : null,
      isAutoGenerated: row.length > 8 && row[8].isNotEmpty ? int.parse(row[8]) : 0,
      createdAtMillis: row.length > 9 && row[9].isNotEmpty ? int.parse(row[9]) : DateTime.now().millisecondsSinceEpoch,
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'subjectName': subjectName,
        'subjectId': subjectId,
        'scheduleId': scheduleId,
        'dateMillis': dateMillis,
        'status': status,
        'note': note,
        'markedAtMillis': markedAtMillis,
        'isAutoGenerated': isAutoGenerated,
        'createdAtMillis': createdAtMillis,
      };

  factory AttendanceRecord.fromMap(Map<String, dynamic> map) => AttendanceRecord(
        id: map['id'] as int?,
        subjectName: map['subjectName'] as String,
        subjectId: map['subjectId'] as int?,
        scheduleId: map['scheduleId'] as int?,
        dateMillis: map['dateMillis'] as int,
        status: map['status'] as String,
        note: map['note'] as String?,
        markedAtMillis: map['markedAtMillis'] as int?,
        isAutoGenerated: (map['isAutoGenerated'] as int?) ?? 0,
        createdAtMillis: map['createdAtMillis'] as int,
      );
}

class TimetableEntry {
  final int? id;
  final String subjectName;
  final String classType;
  final int dayOfWeek;
  final int startTimeMinutes;
  final int endTimeMinutes;
  final String? room;
  final String? professor;
  final String colorHex;
  final int isRecurring;
  final int? startDateMillis;
  final int? endDateMillis;
  final String? note;
  final int createdAtMillis;

  const TimetableEntry({
    this.id,
    required this.subjectName,
    this.classType = 'lecture',
    required this.dayOfWeek,
    required this.startTimeMinutes,
    required this.endTimeMinutes,
    this.room,
    this.professor,
    this.colorHex = '#2196F3',
    this.isRecurring = 1,
    this.startDateMillis,
    this.endDateMillis,
    this.note,
    required this.createdAtMillis,
  });

  static List<String> get csvHeaders => [
        'id',
        'subjectName',
        'classType',
        'dayOfWeek',
        'startTimeMinutes',
        'endTimeMinutes',
        'room',
        'professor',
        'colorHex',
        'isRecurring',
        'startDateMillis',
        'endDateMillis',
        'note',
        'createdAtMillis',
      ];

  List<String> toCsvRow() => [
        id?.toString() ?? '',
        subjectName,
        classType,
        dayOfWeek.toString(),
        startTimeMinutes.toString(),
        endTimeMinutes.toString(),
        room ?? '',
        professor ?? '',
        colorHex,
        isRecurring.toString(),
        startDateMillis?.toString() ?? '',
        endDateMillis?.toString() ?? '',
        note ?? '',
        createdAtMillis.toString(),
      ];

  factory TimetableEntry.fromCsvRow(List<String> row) {
    if (row.length < 5) {
      throw FormatException('TimetableEntry CSV row must have at least 5 columns, got ${row.length}');
    }
    return TimetableEntry(
      id: row[0].isNotEmpty ? int.parse(row[0]) : null,
      subjectName: row[1],
      classType: row.length > 2 && row[2].isNotEmpty ? row[2] : 'lecture',
      dayOfWeek: int.parse(row[3]),
      startTimeMinutes: int.parse(row[4]),
      endTimeMinutes: row.length > 5 ? int.parse(row[5]) : int.parse(row[4]),
      room: row.length > 6 ? (row[6].isNotEmpty ? row[6] : null) : null,
      professor: row.length > 7 ? (row[7].isNotEmpty ? row[7] : null) : null,
      colorHex: row.length > 8 && row[8].isNotEmpty ? row[8] : '#2196F3',
      isRecurring: row.length > 9 && row[9].isNotEmpty ? int.parse(row[9]) : 1,
      startDateMillis: row.length > 10 && row[10].isNotEmpty ? int.parse(row[10]) : null,
      endDateMillis: row.length > 11 && row[11].isNotEmpty ? int.parse(row[11]) : null,
      note: row.length > 12 ? (row[12].isNotEmpty ? row[12] : null) : null,
      createdAtMillis: row.length > 13 && row[13].isNotEmpty ? int.parse(row[13]) : DateTime.now().millisecondsSinceEpoch,
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'subjectName': subjectName,
        'classType': classType,
        'dayOfWeek': dayOfWeek,
        'startTimeMinutes': startTimeMinutes,
        'endTimeMinutes': endTimeMinutes,
        'room': room,
        'professor': professor,
        'colorHex': colorHex,
        'isRecurring': isRecurring,
        'startDateMillis': startDateMillis,
        'endDateMillis': endDateMillis,
        'note': note,
        'createdAtMillis': createdAtMillis,
      };

  factory TimetableEntry.fromMap(Map<String, dynamic> map) => TimetableEntry(
        id: map['id'] as int?,
        subjectName: map['subjectName'] as String,
        classType: (map['classType'] as String?) ?? 'lecture',
        dayOfWeek: map['dayOfWeek'] as int,
        startTimeMinutes: map['startTimeMinutes'] as int,
        endTimeMinutes: map['endTimeMinutes'] as int,
        room: map['room'] as String?,
        professor: map['professor'] as String?,
        colorHex: (map['colorHex'] as String?) ?? '#2196F3',
        isRecurring: (map['isRecurring'] as int?) ?? 1,
        startDateMillis: map['startDateMillis'] as int?,
        endDateMillis: map['endDateMillis'] as int?,
        note: map['note'] as String?,
        createdAtMillis: map['createdAtMillis'] as int,
      );
}

class PdfPlaceholderService {
  static Future<String> generateTextReport({
    required String title,
    required String subtitle,
    required List<String> headers,
    required List<List<String>> rows,
  }) async {
    final buffer = StringBuffer();
    buffer.writeln('=' * 60);
    buffer.writeln(title);
    buffer.writeln(subtitle);
    buffer.writeln('=' * 60);
    buffer.writeln();
    buffer.writeln(headers.join(' | '));
    buffer.writeln('-' * 60);
    for (final row in rows) {
      buffer.writeln(row.join(' | '));
    }
    buffer.writeln();
    buffer.writeln('Generated: ${DateTime.now().toIso8601String()}');
    buffer.writeln('=' * 60);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'report_$timestamp.txt';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(buffer.toString(), encoding: utf8);
    return file.path;
  }
}

// ==================== MAIN SERVICE CLASS ====================
class ExportImportService {
  ExportImportService._();

  static String _computeChecksum(String data) {
    final bytes = utf8.encode(data);
    final digest = sha256.convert(bytes);
    return digest.toString();
  }

  static Future<String> _writeZipFile({
    required String exportType,
    required Map<String, dynamic> dataObject, // ← now takes object, not string
    required String fileName,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final filePath = p.join(dir.path, fileName);

    // Serialize data first
    final jsonString = const JsonEncoder.withIndent('  ').convert(dataObject);
    final checksum = _computeChecksum(jsonString);

    // Build manifest
    final manifest = {
      'exportVersion': _kExportVersion,
      'appName': _kAppName,
      'appVersion': _kAppVersion,
      'exportedAt': DateTime.now().toUtc().toIso8601String(),
      'exportType': exportType,
      'checksum': checksum,
    };

    final manifestJson = const JsonEncoder.withIndent('  ').convert(manifest);

    // Encode both as UTF-8 bytes
    final dataBytes = utf8.encode(jsonString);
    final manifestBytes = utf8.encode(manifestJson);

    // Create ZIP
    final archive = Archive()
      ..addFile(ArchiveFile('data.json', dataBytes.length, dataBytes))
      ..addFile(ArchiveFile('manifest.json', manifestBytes.length, manifestBytes));

    final zipEncoder = ZipEncoder();
    final zipData = zipEncoder.encode(archive);
    if (zipData == null) {
      throw Exception('ZIP encoding failed: returned null');
    }

    // Write to disk
    final file = File(filePath);
    await file.writeAsBytes(zipData);

    // 🔒 CRITICAL: Verify the file is readable and valid
    final testRead = await _readZipFile(filePath);
    if (testRead['exportType'] != exportType) {
      throw Exception('Verification failed: exportType mismatch after write');
    }
    if (testRead['checksum'] != checksum) {
      throw Exception('Verification failed: checksum mismatch after write');
    }

    return filePath;
  }

  static Future<Map<String, dynamic>> _readZipFile(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File not found: $filePath');
    }
    final bytes = await file.readAsBytes();
    if (bytes.isEmpty) {
      throw Exception('File is empty (0 bytes): $filePath');
    }

    final archive = ZipDecoder().decodeBytes(bytes);
    if (archive.isEmpty) {
      throw Exception('Corrupted backup: archive is empty');
    }

    String? dataString;
    String? manifestString;

    for (final af in archive) {
      if (af.name == 'data.json') {
        if (af.content is List<int>) {
          dataString = utf8.decode(af.content as List<int>);
        } else {
          throw Exception('data.json content is not List<int>');
        }
      } else if (af.name == 'manifest.json') {
        if (af.content is List<int>) {
          manifestString = utf8.decode(af.content as List<int>);
        } else {
          throw Exception('manifest.json content is not List<int>');
        }
      }
    }

    if (dataString == null) throw Exception('data.json missing in ZIP');
    if (manifestString == null) throw Exception('manifest.json missing in ZIP');

    final manifest = jsonDecode(manifestString) as Map<String, dynamic>;
    final storedChecksum = manifest['checksum'] as String?;
    if (storedChecksum == null) throw Exception('checksum missing in manifest');

    final computedChecksum = _computeChecksum(dataString);
    if (computedChecksum != storedChecksum) {
      throw Exception('Checksum mismatch: expected $storedChecksum, got $computedChecksum');
    }

    final exportType = manifest['exportType'] as String?;
    if (exportType == null) throw Exception('exportType missing in manifest');

    final data = jsonDecode(dataString) as Map<String, dynamic>;

    return {
      'exportType': exportType,
      'data': data,
      'manifest': manifest,
    };
  }

  static bool _isZipFile(String filePath) {
    final ext = p.extension(filePath).toLowerCase();
    return ext == '.zip' || ext == '.ecbackup';
  }

  // ==================== EXPORT METHODS ====================
  static Future<ExportResult> exportToJson() async {
    try {
      final events = await DatabaseHelper.instance.getAllEventsSorted();
      final jsonList = events.map((e) => e.toJson()).toList();

      final dataObject = {
        'exportVersion': _kExportVersion,
        'appName': _kAppName,
        'appVersion': _kAppVersion,
        'exportedAt': DateTime.now().toUtc().toIso8601String(),
        'exportType': 'events',
        'events': jsonList,
      };

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = 'event_countdown_export_$timestamp.ecbackup';
      final path = await _writeZipFile(
        exportType: 'events',
        dataObject: dataObject,
        fileName: fileName,
      );

      final file = File(path);
      final fileSize = await file.length();

      return ExportResult(
        success: true,
        filePath: path,
        eventCount: events.length,
        totalTableCount: 1,
        fileSizeBytes: fileSize,
        exportedAt: DateTime.now(),
        exportType: 'events',
        checksum: _computeChecksum(const JsonEncoder().convert(jsonList)),
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportToJson error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        errorMessage: 'Export failed: $e',
        exportedAt: DateTime.now(),
        exportType: 'events',
      );
    }
  }

  static Future<ExportResult> exportAllData() async {
    try {
      final allData = await DatabaseHelper.instance.exportAllTables();
      final eventCount = (allData['events'] ?? []).length;
      final totalRows = allData.values.fold<int>(0, (sum, rows) => sum + rows.length);

      final dataObject = {
        'exportVersion': _kExportVersion,
        'appName': _kAppName,
        'appVersion': _kAppVersion,
        'exportedAt': DateTime.now().toUtc().toIso8601String(),
        'exportType': 'full',
        'tables': allData,
      };

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = 'event_countdown_full_export_$timestamp.ecbackup';
      final path = await _writeZipFile(
        exportType: 'full',
        dataObject: dataObject,
        fileName: fileName,
      );

      final file = File(path);
      final fileSize = await file.length();

      return ExportResult(
        success: true,
        filePath: path,
        eventCount: eventCount,
        totalTableCount: allData.length,
        fileSizeBytes: fileSize,
        exportedAt: DateTime.now(),
        exportType: 'full',
        checksum: _computeChecksum(const JsonEncoder().convert(allData)),
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportAllData error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        errorMessage: 'Full export failed: $e',
        exportedAt: DateTime.now(),
        exportType: 'full',
      );
    }
  }

  // ==================== SHARE & SAVE ====================
  static Future<ExportResult> exportAndShareEvents() async {
    final result = await exportToJson();
    if (!result.success || result.filePath == null) return result;
    try {
      final xFile = XFile(result.filePath!, mimeType: 'application/octet-stream', name: p.basename(result.filePath!));
      await Share.shareXFiles([xFile], subject: 'Event Countdown Export');
      return result;
    } catch (e) {
      return ExportResult(
        success: false,
        filePath: result.filePath,
        errorMessage: 'Sharing failed: $e\nFile saved at: ${result.filePath}',
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
  }

  static Future<ExportResult> saveExportToDevice() async {
    final result = await exportToJson();
    if (!result.success || result.filePath == null) return result;
    try {
      final fileName = p.basename(result.filePath!);
      final outputPath = await FilePicker.platform.saveFile(
        dialogTitle: 'Save Event Export',
        fileName: fileName,
        type: FileType.custom,
        allowedExtensions: ['ecbackup'],
      );
      if (outputPath == null) {
        return ExportResult(success: false, errorMessage: 'Save cancelled', filePath: result.filePath);
      }
      final bytes = await File(result.filePath!).readAsBytes();
      await File(outputPath).writeAsBytes(bytes);
      return ExportResult(
        success: true,
        filePath: outputPath,
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: bytes.length,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    } catch (e) {
      return ExportResult(
        success: false,
        errorMessage: 'Save failed: $e',
        filePath: result.filePath,
      );
    }
  }

  // ==================== IMPORT ====================
  static Future<int> importFromJson(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) throw Exception('File not found: $filePath');
    final fileSize = await file.length();
    if (fileSize == 0) throw Exception('File is empty (0 bytes)');

    late List<dynamic> eventList;

    if (_isZipFile(filePath)) {
      final zipData = await _readZipFile(filePath);
      final exportType = zipData['exportType'] as String?;
      if (exportType != 'events') {
        throw Exception('This is a full backup. Use "Import All Data" instead.');
      }
      final data = zipData['data'] as Map<String, dynamic>;
      if (data.containsKey('events')) {
        eventList = data['events'] as List;
      } else if (data is List) {
        eventList = data;
      } else {
        throw Exception('Invalid data structure: expected events list');
      }
    } else {
      final contents = await file.readAsString();
      final decoded = jsonDecode(contents);
      if (decoded is List) {
        eventList = decoded;
      } else if (decoded is Map && decoded.containsKey('events')) {
        eventList = decoded['events'] as List;
      } else {
        throw Exception('Invalid JSON: expected list or map with "events" key');
      }
    }

    final events = <Event>[];
    final errors = <String>[];

    for (var i = 0; i < eventList.length; i++) {
      final item = eventList[i];
      if (item is! Map) {
        errors.add('Index $i: not a Map');
        continue;
      }
      try {
        final event = Event.fromJson(Map<String, dynamic>.from(item));
        events.add(event);
      } catch (e) {
        errors.add('Index $i: $e');
      }
    }

    if (errors.isNotEmpty && events.isEmpty) {
      throw FormatException('All ${eventList.length} events failed to parse:\n${errors.take(5).join('\n')}');
    }
    if (events.isEmpty) throw Exception('No valid events found');

    // Backup before import
    final backup = await DatabaseHelper.instance.getAllEventsSorted();
    try {
      await DatabaseHelper.instance.replaceAllEvents(events);
    } catch (e) {
      await DatabaseHelper.instance.replaceAllEvents(backup);
      throw Exception('Import failed. Restored backup. Error: $e');
    }

    return events.length;
  }

  static Future<void> importAllData(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) throw Exception('File not found: $filePath');
    final fileSize = await file.length();
    if (fileSize == 0) throw Exception('File is empty (0 bytes)');

    late Map<String, dynamic> data;

    if (_isZipFile(filePath)) {
      final zipData = await _readZipFile(filePath);
      final exportType = zipData['exportType'] as String?;
      if (exportType != 'full') {
        throw Exception('This is an events-only backup. Use "Import Events" instead.');
      }
      data = zipData['data'] as Map<String, dynamic>;
    } else {
      final contents = await file.readAsString();
      data = jsonDecode(contents) as Map<String, dynamic>;
    }

    final tablesData = data['tables'];
    if (tablesData is! Map) {
      throw Exception('Missing or invalid "tables" key in export');
    }

    final typedTables = <String, List<Map<String, dynamic>>>{};
    for (final entry in tablesData.entries) {
      final key = entry.key;
      final value = entry.value;
      if (value is! List) {
        throw Exception('Table "$key" is not a list');
      }
      typedTables[key] = value.cast<Map<String, dynamic>>();
    }

    // Validate events
    if (typedTables.containsKey('events')) {
      for (var i = 0; i < typedTables['events']!.length; i++) {
        try {
          Event.fromJson(typedTables['events']![i]);
        } catch (e) {
          throw FormatException('Invalid event at index $i: $e');
        }
      }
    }

    // Backup
    final backup = await DatabaseHelper.instance.exportAllTables();
    try {
      await DatabaseHelper.instance.importAllTables(typedTables);
    } catch (e) {
      await DatabaseHelper.instance.importAllTables(backup);
      throw Exception('Import failed. Restored backup. Error: $e');
    }
  }

  // ==================== CSV & PDF PLACEHOLDERS (unchanged, safe) ====================
  static Future<String> exportAttendanceToCsv(List<AttendanceRecord> records) async {
    final rows = <List<String>>[
      AttendanceRecord.csvHeaders,
      ...records.map((r) => r.toCsvRow()),
    ];
    final csvContent = _CsvHelper.encode(rows);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'attendance_report_$timestamp.csv';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(csvContent, encoding: utf8);
    return file.path;
  }

  static Future<String> exportTimetableToCsv(List<TimetableEntry> entries) async {
    final rows = <List<String>>[
      TimetableEntry.csvHeaders,
      ...entries.map((e) => e.toCsvRow()),
    ];
    final csvContent = _CsvHelper.encode(rows);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'timetable_export_$timestamp.csv';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(csvContent, encoding: utf8);
    return file.path;
  }

  static Future<String> exportAttendanceToPdfPlaceholder(List<AttendanceRecord> records) async {
    return PdfPlaceholderService.generateTextReport(
      title: 'ATTENDANCE REPORT',
      subtitle: 'Event Countdown App',
      headers: AttendanceRecord.csvHeaders,
      rows: records.map((r) => r.toCsvRow()).toList(),
    );
  }

  static Future<String> exportTimetableToPdfPlaceholder(List<TimetableEntry> entries) async {
    return PdfPlaceholderService.generateTextReport(
      title: 'TIMETABLE REPORT',
      subtitle: 'Event Countdown App',
      headers: TimetableEntry.csvHeaders,
      rows: entries.map((e) => e.toCsvRow()).toList(),
    );
  }

  // ==================== UTILITIES ====================
  static Future<List<AttendanceRecord>> importAttendanceFromCsv(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) throw Exception('File not found');
    final contents = await file.readAsString(encoding: utf8);
    final rows = _CsvHelper.decode(contents);
    if (rows.isEmpty) throw Exception('No data rows');
    var startIndex = 0;
    final firstRow = rows.first.map((c) => c.toLowerCase().trim()).toList();
    final expected = AttendanceRecord.csvHeaders.map((h) => h.toLowerCase()).toList();
    if (_rowsMatchHeaders(firstRow, expected)) startIndex = 1;
    final records = <AttendanceRecord>[];
    final errors = <String>[];
    for (var i = startIndex; i < rows.length; i++) {
      try {
        records.add(AttendanceRecord.fromCsvRow(rows[i]));
      } catch (e) {
        errors.add('Row ${i+1}: $e');
      }
    }
    if (errors.isNotEmpty && records.isEmpty) throw FormatException('All rows failed');
    return records;
  }

  static bool _rowsMatchHeaders(List<String> row, List<String> headers) {
    if (row.length < headers.length) return false;
    for (var i = 0; i < headers.length; i++) if (row[i] != headers[i]) return false;
    return true;
  }

  // Remaining methods (importTimetableFromCsv, pickers, etc.) omitted for brevity — they are safe and unchanged.
  // You can restore them from your original file if needed — they don’t cause the ZIP issue.
}
