// FILE: lib/services/export_import_service.dart
import 'dart:io';
import 'dart:convert';
import 'dart:math';
import 'package:archive/archive.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:file_picker/file_picker.dart';
import 'package:event_countdown/database_helper.dart';
import 'package:event_countdown/models/event.dart';

// ==================== CONSTANTS ====================
const String _kAppName = 'StudyFlow'; // Matched from settings_screen title
const String _kAppVersion = '1.0.0';
const int _kExportVersion = 2;

// ==================== HELPER CLASSES ====================

class ExportResult {
  final bool success;
  final String? filePath;
  final int? eventCount;
  final int? totalTableCount;
  final int? fileSizeBytes;
  final DateTime? exportedAt;
  final String? exportType;
  final String? checksum;
  final String? errorMessage;

  const ExportResult({
    required this.success,
    this.filePath,
    this.eventCount,
    this.totalTableCount,
    this.fileSizeBytes,
    this.exportedAt,
    this.exportType,
    this.checksum,
    this.errorMessage,
  });

  String get fileSizeReadable {
    final bytes = fileSizeBytes;
    if (bytes == null || bytes <= 0) return '0 B';
    const suffixes = ['B', 'KB', 'MB', 'GB', 'TB'];
    final i = (log(bytes.toDouble()) / log(1024)).floor().clamp(0, suffixes.length - 1);
    final size = bytes / pow(1024, i);
    return '${size.toStringAsFixed(i == 0 ? 0 : 1)} ${suffixes[i]}';
  }
}

class ImportPreview {
  final String exportType;
  final String appVersion;
  final DateTime? exportedAt;
  final Map<String, int> tableRowCounts;
  final int totalRows;
  final String? checksum;
  final bool checksumValid;
  final List<String> warnings;

  const ImportPreview({
    required this.exportType,
    required this.appVersion,
    this.exportedAt,
    required this.tableRowCounts,
    required this.totalRows,
    this.checksum,
    required this.checksumValid,
    required this.warnings,
  });
}

class _CsvHelper {
  static String encode(List<List<String>> rows) {
    final buffer = StringBuffer();
    for (final row in rows) {
      final escaped = row.map((field) {
        if (field.contains(',') || field.contains('"') || field.contains('\n')) {
          final escapedField = field.replaceAll('"', '""');
          return '"$escapedField"';
        }
        return field;
      }).join(',');
      buffer.writeln(escaped);
    }
    return buffer.toString();
  }

  static List<List<String>> decode(String csv) {
    final rows = <List<String>>[];
    final lines = csv.split('\n');
    for (var line in lines) {
      line = line.trim();
      if (line.isEmpty) continue;
      final fields = <String>[];
      var current = StringBuffer();
      var inQuotes = false;
      for (var i = 0; i < line.length; i++) {
        final char = line[i];
        if (char == '"') {
          if (inQuotes && i + 1 < line.length && line[i + 1] == '"') {
            current.write('"');
            i++; // skip next quote
          } else {
            inQuotes = !inQuotes;
          }
        } else if (char == ',' && !inQuotes) {
          fields.add(current.toString());
          current = StringBuffer();
        } else {
          current.write(char);
        }
      }
      fields.add(current.toString());
      rows.add(fields);
    }
    return rows;
  }
}

class AttendanceRecord {
  final int? id;
  final String subjectName;
  final int? subjectId;
  final int? scheduleId;
  final int dateMillis;
  final String status;
  final String? note;
  final int? markedAtMillis;
  final int isAutoGenerated;
  final int createdAtMillis;

  const AttendanceRecord({
    this.id,
    required this.subjectName,
    this.subjectId,
    this.scheduleId,
    required this.dateMillis,
    required this.status,
    this.note,
    this.markedAtMillis,
    this.isAutoGenerated = 0,
    required this.createdAtMillis,
  });

  static List<String> get csvHeaders => [
        'id',
        'subjectName',
        'subjectId',
        'scheduleId',
        'dateMillis',
        'status',
        'note',
        'markedAtMillis',
        'isAutoGenerated',
        'createdAtMillis',
      ];

  List<String> toCsvRow() => [
        id?.toString() ?? '',
        subjectName,
        subjectId?.toString() ?? '',
        scheduleId?.toString() ?? '',
        dateMillis.toString(),
        status,
        note ?? '',
        markedAtMillis?.toString() ?? '',
        isAutoGenerated.toString(),
        createdAtMillis.toString(),
      ];

  factory AttendanceRecord.fromCsvRow(List<String> row) {
    if (row.length < 6) {
      throw FormatException('AttendanceRecord CSV row must have at least 6 columns, got ${row.length}');
    }
    return AttendanceRecord(
      id: row[0].isNotEmpty ? int.parse(row[0]) : null,
      subjectName: row[1],
      subjectId: row[2].isNotEmpty ? int.parse(row[2]) : null,
      scheduleId: row[3].isNotEmpty ? int.parse(row[3]) : null,
      dateMillis: int.parse(row[4]),
      status: row[5],
      note: row.length > 6 ? (row[6].isNotEmpty ? row[6] : null) : null,
      markedAtMillis: row.length > 7 && row[7].isNotEmpty ? int.parse(row[7]) : null,
      isAutoGenerated: row.length > 8 && row[8].isNotEmpty ? int.parse(row[8]) : 0,
      createdAtMillis: row.length > 9 && row[9].isNotEmpty ? int.parse(row[9]) : DateTime.now().millisecondsSinceEpoch,
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'subjectName': subjectName,
        'subjectId': subjectId,
        'scheduleId': scheduleId,
        'dateMillis': dateMillis,
        'status': status,
        'note': note,
        'markedAtMillis': markedAtMillis,
        'isAutoGenerated': isAutoGenerated,
        'createdAtMillis': createdAtMillis,
      };

  factory AttendanceRecord.fromMap(Map<String, dynamic> map) => AttendanceRecord(
        id: map['id'] as int?,
        subjectName: map['subjectName'] as String,
        subjectId: map['subjectId'] as int?,
        scheduleId: map['scheduleId'] as int?,
        dateMillis: map['dateMillis'] as int,
        status: map['status'] as String,
        note: map['note'] as String?,
        markedAtMillis: map['markedAtMillis'] as int?,
        isAutoGenerated: (map['isAutoGenerated'] as int?) ?? 0,
        createdAtMillis: map['createdAtMillis'] as int,
      );
}

class TimetableEntry {
  final int? id;
  final String subjectName;
  final String classType;
  final int dayOfWeek;
  final int startTimeMinutes;
  final int endTimeMinutes;
  final String? room;
  final String? professor;
  final String colorHex;
  final int isRecurring;
  final int? startDateMillis;
  final int? endDateMillis;
  final String? note;
  final int createdAtMillis;

  const TimetableEntry({
    this.id,
    required this.subjectName,
    this.classType = 'lecture',
    required this.dayOfWeek,
    required this.startTimeMinutes,
    required this.endTimeMinutes,
    this.room,
    this.professor,
    this.colorHex = '#2196F3',
    this.isRecurring = 1,
    this.startDateMillis,
    this.endDateMillis,
    this.note,
    required this.createdAtMillis,
  });

  static List<String> get csvHeaders => [
        'id',
        'subjectName',
        'classType',
        'dayOfWeek',
        'startTimeMinutes',
        'endTimeMinutes',
        'room',
        'professor',
        'colorHex',
        'isRecurring',
        'startDateMillis',
        'endDateMillis',
        'note',
        'createdAtMillis',
      ];

  List<String> toCsvRow() => [
        id?.toString() ?? '',
        subjectName,
        classType,
        dayOfWeek.toString(),
        startTimeMinutes.toString(),
        endTimeMinutes.toString(),
        room ?? '',
        professor ?? '',
        colorHex,
        isRecurring.toString(),
        startDateMillis?.toString() ?? '',
        endDateMillis?.toString() ?? '',
        note ?? '',
        createdAtMillis.toString(),
      ];

  factory TimetableEntry.fromCsvRow(List<String> row) {
    if (row.length < 5) {
      throw FormatException('TimetableEntry CSV row must have at least 5 columns, got ${row.length}');
    }
    return TimetableEntry(
      id: row[0].isNotEmpty ? int.parse(row[0]) : null,
      subjectName: row[1],
      classType: row.length > 2 && row[2].isNotEmpty ? row[2] : 'lecture',
      dayOfWeek: int.parse(row[3]),
      startTimeMinutes: int.parse(row[4]),
      endTimeMinutes: row.length > 5 ? int.parse(row[5]) : int.parse(row[4]),
      room: row.length > 6 ? (row[6].isNotEmpty ? row[6] : null) : null,
      professor: row.length > 7 ? (row[7].isNotEmpty ? row[7] : null) : null,
      colorHex: row.length > 8 && row[8].isNotEmpty ? row[8] : '#2196F3',
      isRecurring: row.length > 9 && row[9].isNotEmpty ? int.parse(row[9]) : 1,
      startDateMillis: row.length > 10 && row[10].isNotEmpty ? int.parse(row[10]) : null,
      endDateMillis: row.length > 11 && row[11].isNotEmpty ? int.parse(row[11]) : null,
      note: row.length > 12 ? (row[12].isNotEmpty ? row[12] : null) : null,
      createdAtMillis: row.length > 13 && row[13].isNotEmpty ? int.parse(row[13]) : DateTime.now().millisecondsSinceEpoch,
    );
  }

  Map<String, dynamic> toMap() => {
        'id': id,
        'subjectName': subjectName,
        'classType': classType,
        'dayOfWeek': dayOfWeek,
        'startTimeMinutes': startTimeMinutes,
        'endTimeMinutes': endTimeMinutes,
        'room': room,
        'professor': professor,
        'colorHex': colorHex,
        'isRecurring': isRecurring,
        'startDateMillis': startDateMillis,
        'endDateMillis': endDateMillis,
        'note': note,
        'createdAtMillis': createdAtMillis,
      };

  factory TimetableEntry.fromMap(Map<String, dynamic> map) => TimetableEntry(
        id: map['id'] as int?,
        subjectName: map['subjectName'] as String,
        classType: (map['classType'] as String?) ?? 'lecture',
        dayOfWeek: map['dayOfWeek'] as int,
        startTimeMinutes: map['startTimeMinutes'] as int,
        endTimeMinutes: map['endTimeMinutes'] as int,
        room: map['room'] as String?,
        professor: map['professor'] as String?,
        colorHex: (map['colorHex'] as String?) ?? '#2196F3',
        isRecurring: (map['isRecurring'] as int?) ?? 1,
        startDateMillis: map['startDateMillis'] as int?,
        endDateMillis: map['endDateMillis'] as int?,
        note: map['note'] as String?,
        createdAtMillis: map['createdAtMillis'] as int,
      );
}

class PdfPlaceholderService {
  static Future<String> generateTextReport({
    required String title,
    required String subtitle,
    required List<String> headers,
    required List<List<String>> rows,
  }) async {
    final buffer = StringBuffer();
    buffer.writeln('=' * 60);
    buffer.writeln(title);
    buffer.writeln(subtitle);
    buffer.writeln('=' * 60);
    buffer.writeln();
    buffer.writeln(headers.join(' | '));
    buffer.writeln('-' * 60);
    for (final row in rows) {
      buffer.writeln(row.join(' | '));
    }
    buffer.writeln();
    buffer.writeln('Generated: ${DateTime.now().toIso8601String()}');
    buffer.writeln('=' * 60);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'report_$timestamp.txt';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(buffer.toString(), encoding: utf8);
    return file.path;
  }
}

class BackupWorkManager {
  static void initialize() {
    if (kDebugMode) debugPrint('BackupWorkManager initialized');
  }

  static Future<void> registerMonthlyBackup() async {
    if (kDebugMode) debugPrint('Monthly backup registered');
  }

  static Future<void> cancelMonthlyBackup() async {
    if (kDebugMode) debugPrint('Monthly backup cancelled');
  }
}

// ==================== MAIN SERVICE CLASS ====================

class ExportImportService {
  ExportImportService._();

  // ==================== HELPER METHODS ====================

  static String _computeChecksum(String data) {
    final bytes = utf8.encode(data);
    final digest = sha256.convert(bytes);
    return digest.toString();
  }

  static String _safeString(dynamic value, String defaultValue) {
    if (value is String) return value;
    if (value != null) return value.toString();
    return defaultValue;
  }

  static DateTime? _safeDateTimeParse(dynamic value) {
    if (value is DateTime) return value;
    if (value is String) {
      try {
        return DateTime.parse(value);
      } catch (_) {
        return null;
      }
    }
    return null;
  }

  static Future<String> _writeZipFile({
    required String exportType,
    required String dataJsonString,
    required String fileName,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final filePath = p.join(dir.path, fileName);

    final checksum = _computeChecksum(dataJsonString);
    final manifest = {
      'exportVersion': _kExportVersion,
      'appName': _kAppName,
      'appVersion': _kAppVersion,
      'exportedAt': DateTime.now().toUtc().toIso8601String(),
      'exportType': exportType,
      'checksum': checksum,
    };

    final manifestJson = const JsonEncoder.withIndent('  ').convert(manifest);

    final dataBytes = utf8.encode(dataJsonString);
    final manifestBytes = utf8.encode(manifestJson);

    final archive = Archive()
      ..addFile(ArchiveFile('data.json', dataBytes.length, dataBytes))
      ..addFile(ArchiveFile('manifest.json', manifestBytes.length, manifestBytes));

    final zipEncoder = ZipEncoder();
    final zipData = zipEncoder.encode(archive);
    if (zipData == null) {
      throw Exception('Failed to encode ZIP archive');
    }

    final file = File(filePath);
    await file.writeAsBytes(zipData);

    // Verify file was written correctly
    if (!await file.exists()) {
      throw Exception('Failed to write backup file to disk');
    }
    final fileSize = await file.length();
    if (fileSize == 0) {
      throw Exception('Backup file was written but has 0 bytes');
    }

    return filePath;
  }

  static Future<Map<String, dynamic>> _readZipFile(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File does not exist: $filePath');
    }
    final bytes = await file.readAsBytes();
    if (bytes.isEmpty) {
      throw Exception('File is empty (0 bytes): $filePath');
    }

    final archive = ZipDecoder().decodeBytes(bytes);
    if (archive.isEmpty) {
      throw Exception('Corrupted backup: archive is empty');
    }

    String? dataString;
    String? manifestString;

    for (final archiveFile in archive) {
      if (archiveFile.name == 'data.json') {
        if (archiveFile.content is List<int>) {
          dataString = utf8.decode(archiveFile.content as List<int>);
        } else {
          throw Exception('Corrupted backup: data.json content is not binary');
        }
      } else if (archiveFile.name == 'manifest.json') {
        if (archiveFile.content is List<int>) {
          manifestString = utf8.decode(archiveFile.content as List<int>);
        } else {
          throw Exception('Corrupted backup: manifest.json content is not binary');
        }
      }
    }

    if (dataString == null) {
      throw Exception('Corrupted backup: data.json missing from archive');
    }
    if (manifestString == null) {
      throw Exception('Corrupted backup: manifest.json missing from archive');
    }

    final manifest = jsonDecode(manifestString) as Map<String, dynamic>;
    final storedChecksum = manifest['checksum'];
    if (storedChecksum == null) {
      throw Exception('Corrupted backup: checksum missing from manifest');
    }

    final computedChecksum = _computeChecksum(dataString);
    if (computedChecksum != storedChecksum) {
      throw Exception('Corrupted backup (checksum mismatch). The file may have been tampered with or is incomplete.');
    }

    final exportType = manifest['exportType'];
    if (exportType == null) {
      throw Exception('Corrupted backup: exportType missing from manifest');
    }

    final dataObject = jsonDecode(dataString) as Map<String, dynamic>;

    return {
      'exportType': exportType,
      'data': dataObject,
      'manifest': manifest,
    };
  }

  static bool _isZipFile(String filePath) {
    final ext = p.extension(filePath).toLowerCase();
    return ext == '.zip' || ext == '.ecbackup';
  }

  // ==================== EXPORT METHODS ====================

  static Future<ExportResult> exportToJson() async {
    try {
      final events = await DatabaseHelper.instance.getAllEventsSorted();
      final jsonList = events.map((e) => e.toJson()).toList();

      final jsonString = const JsonEncoder.withIndent('  ').convert(jsonList);

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = 'studyflow_export_$timestamp.ecbackup';
      final path = await _writeZipFile(
        exportType: 'events',
        dataJsonString: jsonString,
        fileName: fileName,
      );

      final file = File(path);
      final fileSize = await file.length();

      return ExportResult(
        success: true,
        filePath: path,
        eventCount: events.length,
        totalTableCount: 1,
        fileSizeBytes: fileSize,
        exportedAt: DateTime.now(),
        exportType: 'events',
        checksum: _computeChecksum(jsonList.toString()),
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportToJson error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        errorMessage: 'Export failed: $e',
        exportedAt: DateTime.now(),
        exportType: 'events',
      );
    }
  }

  static Future<ExportResult> exportAllData() async {
    try {
      final allData = await DatabaseHelper.instance.exportAllTables();
      final eventCount = (allData['events'] ?? []).length;
      final totalRows = allData.values.fold<int>(0, (sum, rows) => sum + rows.length);

      final exportMap = {
        'exportVersion': _kExportVersion,
        'appName': _kAppName,
        'appVersion': _kAppVersion,
        'exportedAt': DateTime.now().toUtc().toIso8601String(),
        'tables': allData,
      };

      final jsonString = const JsonEncoder.withIndent('  ').convert(exportMap);

      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = 'studyflow_full_export_$timestamp.ecbackup';
      final path = await _writeZipFile(
        exportType: 'full',
        dataJsonString: jsonString,
        fileName: fileName,
      );

      final file = File(path);
      final fileSize = await file.length();

      return ExportResult(
        success: true,
        filePath: path,
        eventCount: eventCount,
        totalTableCount: allData.length,
        fileSizeBytes: fileSize,
        exportedAt: DateTime.now(),
        exportType: 'full',
        checksum: _computeChecksum(allData.toString()),
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportAllData error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        errorMessage: 'Full export failed: $e',
        exportedAt: DateTime.now(),
        exportType: 'full',
      );
    }
  }

  // ==================== ENHANCED: EXPORT AS PLAIN JSON ====================

  static Future<ExportResult> exportEventsAsPlainJson() async {
    try {
      final events = await DatabaseHelper.instance.getAllEventsSorted();
      final jsonList = events.map((e) => e.toJson()).toList();
      final jsonString = const JsonEncoder.withIndent('  ').convert(jsonList);

      final dir = await getApplicationDocumentsDirectory();
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final fileName = 'studyflow_events_$timestamp.json';
      final file = File('${dir.path}/$fileName');
      await file.writeAsString(jsonString, encoding: utf8);

      final fileSize = await file.length();

      return ExportResult(
        success: true,
        filePath: file.path,
        eventCount: events.length,
        totalTableCount: 1,
        fileSizeBytes: fileSize,
        exportedAt: DateTime.now(),
        exportType: 'events_plain_json',
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportEventsAsPlainJson error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        errorMessage: 'Plain JSON export failed: $e',
        exportedAt: DateTime.now(),
        exportType: 'events_plain_json',
      );
    }
  }

  // ==================== SHARE EXPORT (CRASH-FIXED) ====================

  static Future<ExportResult> exportAndShareEvents() async {
    final result = await exportToJson();
    if (!result.success || result.filePath == null) {
      return result;
    }

    try {
      final xFile = XFile(
        result.filePath!,
        mimeType: 'application/octet-stream',
        name: p.basename(result.filePath!),
      );
      await Share.shareXFiles(
        [xFile],
        subject: 'StudyFlow Export',
        text: 'Here is my StudyFlow export file.',
      );
      return result;
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportAndShareEvents error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        filePath: result.filePath,
        errorMessage: 'Sharing failed: $e\nThe file was saved at: ${result.filePath}',
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
  }

  static Future<ExportResult> exportAndShareAllData() async {
    final result = await exportAllData();
    if (!result.success || result.filePath == null) {
      return result;
    }

    try {
      final xFile = XFile(
        result.filePath!,
        mimeType: 'application/octet-stream',
        name: p.basename(result.filePath!),
      );
      await Share.shareXFiles(
        [xFile],
        subject: 'StudyFlow Full Export',
        text: 'Here is my complete StudyFlow data export.',
      );
      return result;
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('exportAndShareAllData error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        filePath: result.filePath,
        errorMessage: 'Sharing failed: $e\nThe file was saved at: ${result.filePath}',
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
  }

  // ==================== SAVE TO DEVICE (CRASH-FIXED) ====================

  static Future<ExportResult> saveExportToDevice() async {
    final result = await exportToJson();
    if (!result.success || result.filePath == null) {
      return result;
    }

    try {
      final fileName = p.basename(result.filePath!);
      final String? outputPath = await FilePicker.platform.saveFile(
        dialogTitle: 'Save Event Export',
        fileName: fileName,
        type: FileType.custom,
        allowedExtensions: ['ecbackup'],
      );
      if (outputPath == null) {
        return ExportResult(
          success: false,
          filePath: result.filePath,
          errorMessage: 'Save cancelled by user',
          eventCount: result.eventCount,
          totalTableCount: result.totalTableCount,
          fileSizeBytes: result.fileSizeBytes,
          exportedAt: result.exportedAt,
          exportType: result.exportType,
          checksum: result.checksum,
        );
      }
      final fileBytes = await File(result.filePath!).readAsBytes();
      await File(outputPath).writeAsBytes(fileBytes);
      return ExportResult(
        success: true,
        filePath: outputPath,
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: fileBytes.length,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('saveExportToDevice error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        filePath: result.filePath,
        errorMessage: 'Save to device failed: $e',
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
  }

  static Future<ExportResult> saveFullExportToDevice() async {
    final result = await exportAllData();
    if (!result.success || result.filePath == null) {
      return result;
    }

    try {
      final fileName = p.basename(result.filePath!);
      final String? outputPath = await FilePicker.platform.saveFile(
        dialogTitle: 'Save Full Export',
        fileName: fileName,
        type: FileType.custom,
        allowedExtensions: ['ecbackup'],
      );
      if (outputPath == null) {
        return ExportResult(
          success: false,
          filePath: result.filePath,
          errorMessage: 'Save cancelled by user',
          eventCount: result.eventCount,
          totalTableCount: result.totalTableCount,
          fileSizeBytes: result.fileSizeBytes,
          exportedAt: result.exportedAt,
          exportType: result.exportType,
          checksum: result.checksum,
        );
      }
      final fileBytes = await File(result.filePath!).readAsBytes();
      await File(outputPath).writeAsBytes(fileBytes);
      return ExportResult(
        success: true,
        filePath: outputPath,
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: fileBytes.length,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    } catch (e, stackTrace) {
      if (kDebugMode) {
        debugPrint('saveFullExportToDevice error: $e');
        debugPrint(stackTrace.toString());
      }
      return ExportResult(
        success: false,
        filePath: result.filePath,
        errorMessage: 'Save to device failed: $e',
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
  }

  // ==================== ENHANCED: SAVE TO DOWNLOADS ====================

  static Future<String?> _copyToDownloads(String sourcePath) async {
    if (Platform.isAndroid) {
      try {
        final downloadsDir = Directory('/storage/emulated/0/Download');
        if (await downloadsDir.exists()) {
          final fileName = p.basename(sourcePath);
          final destPath = '${downloadsDir.path}/$fileName';
          await File(sourcePath).copy(destPath);
          return destPath;
        }
      } catch (e) {
        if (kDebugMode) debugPrint('Could not copy to Downloads: $e');
      }
    }
    return null;
  }

  static Future<ExportResult> exportAndSaveToDownloads() async {
    final result = await exportToJson();
    if (!result.success || result.filePath == null) {
      return result;
    }
    final downloadPath = await _copyToDownloads(result.filePath!);
    if (downloadPath != null) {
      return ExportResult(
        success: true,
        filePath: downloadPath,
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
    return result;
  }

  static Future<ExportResult> exportAllAndSaveToDownloads() async {
    final result = await exportAllData();
    if (!result.success || result.filePath == null) {
      return result;
    }
    final downloadPath = await _copyToDownloads(result.filePath!);
    if (downloadPath != null) {
      return ExportResult(
        success: true,
        filePath: downloadPath,
        eventCount: result.eventCount,
        totalTableCount: result.totalTableCount,
        fileSizeBytes: result.fileSizeBytes,
        exportedAt: result.exportedAt,
        exportType: result.exportType,
        checksum: result.checksum,
      );
    }
    return result;
  }

  // ==================== IMPORT PREVIEW (NEW) ====================

  static Future<ImportPreview> previewImportFile(String filePath) async {
    final warnings = <String>[];
    try {
      final file = File(filePath);
      if (!await file.exists()) {
        throw Exception('File not found: $filePath');
      }
      final fileSize = await file.length();
      if (fileSize == 0) {
        throw Exception('File is empty (0 bytes)');
      }

      late final Map<String, dynamic> decoded;
      String? exportType;
      String? checksum;
      bool checksumValid = false;

      if (_isZipFile(filePath)) {
        final zipData = await _readZipFile(filePath);
        exportType = zipData['exportType'] as String?;
        final manifest = zipData['manifest'] as Map<String, dynamic>?;
        checksum = manifest?['checksum'] as String?;
        decoded = zipData['data'] as Map<String, dynamic>;
      } else {
        final contents = await file.readAsString();
        if (contents.trim().isEmpty) {
          throw Exception('File is empty');
        }
        decoded = jsonDecode(contents) as Map<String, dynamic>;
        exportType = decoded['exportType'] as String?;
        if (exportType == null && decoded.containsKey('events')) {
          exportType = 'events';
        }
      }

      final appVersion = _safeString(decoded['appVersion'], 'unknown');
      final exportedAt = _safeDateTimeParse(decoded['exportedAt']);

      final tableRowCounts = <String, int>{};
      int totalRows = 0;

      if (decoded.containsKey('tables')) {
        final dataMap = decoded['tables'] as Map<String, dynamic>;
        for (final entry in dataMap.entries) {
          final rows = entry.value;
          if (rows is List) {
            tableRowCounts[entry.key] = rows.length;
            totalRows += rows.length;
          }
        }
      } else if (decoded.containsKey('events')) {
        final events = decoded['events'];
        if (events is List) {
          tableRowCounts['events'] = events.length;
          totalRows = events.length;
        }
      } else if (decoded is List) {
        tableRowCounts['events'] = decoded.length;
        totalRows = decoded.length;
      }

      if (checksum != null) {
        try {
          final dataStr = jsonEncode(decoded['data'] ?? decoded); // Checksum is calculated on the main data part
          checksumValid = _computeChecksum(dataStr) == checksum;
        } catch (_) {
          checksumValid = false;
        }
      }

      if (!checksumValid && checksum != null) {
        warnings.add('Checksum mismatch - file may be corrupted');
      }
      if (tableRowCounts.isEmpty) {
        warnings.add('No data tables found in file');
      }
      final expVersion = decoded['exportVersion'];
      if (expVersion != null && expVersion != _kExportVersion) {
        warnings.add('Unknown export version: $expVersion (expected $_kExportVersion)');
      }

      return ImportPreview(
        exportType: exportType ?? 'unknown',
        appVersion: appVersion,
        exportedAt: exportedAt,
        tableRowCounts: tableRowCounts,
        totalRows: totalRows,
        checksum: checksum,
        checksumValid: checksumValid,
        warnings: warnings,
      );
    } catch (e) {
      return ImportPreview(
        exportType: 'error',
        appVersion: 'unknown',
        exportedAt: DateTime.now(),
        tableRowCounts: {},
        totalRows: 0,
        checksumValid: false,
        warnings: ['Error reading file: $e'],
      );
    }
  }

  // ==================== IMPORT (CRASH-FIXED & ENHANCED) ====================

  static Future<int> importFromJson(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File not found: $filePath');
    }
    final fileSize = await file.length();
    if (fileSize == 0) {
      throw Exception('File is empty (0 bytes): $filePath');
    }

    List<dynamic> eventList = [];

    if (_isZipFile(filePath)) {
      final zipData = await _readZipFile(filePath);
      final exportType = zipData['exportType'] as String?;
      final rawData = zipData['data'];

      if (exportType != 'events' && exportType != 'full') {
        throw Exception('This file is not an events export.');
      }

      if (exportType == 'events') {
        if (rawData is List) {
          eventList = rawData;
        } else if (rawData is Map && rawData.containsKey('events')) {
          eventList = rawData['events'] as List;
        } else {
          throw Exception('Invalid data format for events export.');
        }
      } else if (exportType == 'full') {
        if (rawData is Map<String, dynamic> && rawData.containsKey('tables')) {
          final tables = rawData['tables'] as Map<String, dynamic>;
          if (tables.containsKey('events')) {
            eventList = tables['events'] as List;
          } else {
            throw Exception('Events not found in full export data.');
          }
        } else {
          throw Exception('Invalid data format for full export.');
        }
      }
    } else {
      final contents = await file.readAsString();
      if (contents.trim().isEmpty) {
        throw Exception('File is empty');
      }
      final decoded = jsonDecode(contents);
      if (decoded is List) {
        eventList = decoded;
      } else if (decoded is Map && decoded.containsKey('events')) {
        eventList = decoded['events'] as List;
      } else {
        throw Exception('Invalid JSON format: expected a list of events or a map containing events.');
      }
    }

    final events = <Event>[];
    final errors = <String>[];

    for (var i = 0; i < eventList.length; i++) {
      final item = eventList[i];
      if (item is! Map<String, dynamic>) {
        errors.add('Index $i: expected a map, got ${item.runtimeType}');
        continue;
      }
      try {
        final eventMap = Map<String, dynamic>.from(item);
        final event = Event.fromJson(eventMap);
        events.add(event);
      } catch (e) {
        errors.add('Index $i: $e');
      }
    }

    if (errors.isNotEmpty && events.isEmpty) {
      throw FormatException('All ${eventList.length} events failed to parse:\n${errors.take(5).join('\n')}');
    }

    if (events.isEmpty) {
      throw Exception('No valid events found in file');
    }

    // Create backup before import
    List<Event> backup;
    try {
      backup = await DatabaseHelper.instance.getAllEventsSorted();
    } catch (e) {
      backup = [];
      if (kDebugMode) debugPrint('Could not create backup before import: $e');
    }

    try {
      await DatabaseHelper.instance.replaceAllEvents(events);
    } catch (e) {
      // Restore backup
      if (backup.isNotEmpty) {
        try {
          await DatabaseHelper.instance.replaceAllEvents(backup);
        } catch (restoreError) {
          throw Exception('Import failed AND backup restore failed. Database may be in an inconsistent state. Error: $restoreError');
        }
      }
      throw Exception('Import failed. Database restored from backup. Error: $e');
    }

    return events.length;
  }

  static Future<void> importAllData(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File not found: $filePath');
    }
    final fileSize = await file.length();
    if (fileSize == 0) {
      throw Exception('File is empty (0 bytes): $filePath');
    }

    late final Map<String, dynamic> decoded;

    if (_isZipFile(filePath)) {
      final zipData = await _readZipFile(filePath);
      final exportType = zipData['exportType'] as String?;
      final rawData = zipData['data'];

      if (exportType != 'full') {
        throw Exception('This file is not a full data export. Please use "Import Events" instead if it contains only events.');
      }

      if (rawData is! Map<String, dynamic>) {
        throw Exception('Invalid export format: expected a map inside .ecbackup');
      }
      decoded = rawData;
    } else {
      final contents = await file.readAsString();
      if (contents.trim().isEmpty) {
        throw Exception('File is empty');
      }
      final raw = jsonDecode(contents);
      if (raw is! Map<String, dynamic>) {
        throw Exception('Invalid export format: expected a map');
      }
      decoded = raw;
    }

    final exportVersion = decoded['exportVersion'];
    if (exportVersion != null && exportVersion != _kExportVersion) {
      throw Exception('Unsupported export version: $exportVersion (expected $_kExportVersion)');
    }

    final tablesData = decoded['tables'];
    if (tablesData is! Map<String, dynamic>) {
      throw Exception('Invalid export format: missing or invalid "tables" key');
    }

    final typedTables = <String, List<Map<String, dynamic>>>{};
    for (final entry in (tablesData as Map).entries) {
      final key = entry.key.toString();
      final value = entry.value;
      if (value is! List) {
        throw Exception('Invalid data for table "$key": expected a list, got ${value.runtimeType}');
      }
      try {
        typedTables[key] = value.cast<Map<String, dynamic>>();
      } catch (e) {
        final convertedList = <Map<String, dynamic>>[];
        for (final item in value) {
          if (item is Map<String, dynamic>) {
            convertedList.add(item);
          } else if (item is Map) {
            convertedList.add(Map<String, dynamic>.from(item));
          } else {
             throw Exception('Invalid data for table "$key": item in list is not a map, got ${item.runtimeType}');
          }
        }
        typedTables[key] = convertedList;
      }
    }

    if (typedTables.containsKey('events')) {
      final eventList = typedTables['events']!;
      final errors = <String>[];
      for (var i = 0; i < eventList.length; i++) {
        try {
          Event.fromJson(eventList[i]);
        } catch (e) {
          errors.add('Invalid event at index $i: $e');
        }
      }
      if (errors.isNotEmpty) {
        throw FormatException('Event validation failed:\n${errors.take(10).join('\n')}');
      }
    }

    Map<String, List<Map<String, dynamic>>> backup;
    try {
      backup = await DatabaseHelper.instance.exportAllTables();
    } catch (e) {
      backup = {};
      if (kDebugMode) debugPrint('Could not create backup before import: $e');
    }

    try {
      await DatabaseHelper.instance.importAllTables(typedTables);
    } catch (e) {
      if (backup.isNotEmpty) {
        try {
          await DatabaseHelper.instance.importAllTables(backup);
        } catch (restoreError) {
          throw Exception('Import failed AND backup restore failed. Database may be in an inconsistent state. Error: $restoreError');
        }
      }
      throw Exception('Import failed. Database restored from backup. Error: $e');
    }
  }

  // ==================== PICKER METHODS (USED BY UI) ====================

  static Future<ExportResult> exportEventsFromPicker() async {
     return exportToJson(); // Or implement picker for export destination if needed, but standard is app dir.
  }

  static Future<int> importEventsFromPicker() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['ecbackup', 'json'],
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.isEmpty) {
      throw Exception('No file selected');
    }
    final path = result.files.single.path;
    if (path == null) {
      throw Exception('Could not access file path');
    }
    return importFromJson(path);
  }

  static Future<void> importAllDataFromPicker() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['ecbackup', 'json'],
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.isEmpty) {
      throw Exception('No file selected');
    }
    final path = result.files.single.path;
    if (path == null) {
      throw Exception('Could not access file path');
    }
    return importAllData(path);
  }

  // ==================== ATTENDANCE CSV EXPORT ====================

  static Future<String> exportAttendanceToCsv(List<AttendanceRecord> records) async {
    final rows = <List<String>>[
      AttendanceRecord.csvHeaders,
      ...records.map((r) => r.toCsvRow()),
    ];
    final csvContent = _CsvHelper.encode(rows);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'attendance_report_$timestamp.csv';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(csvContent, encoding: utf8);
    return file.path;
  }

  static Future<void> exportAndShareAttendance(List<AttendanceRecord> records) async {
    final path = await exportAttendanceToCsv(records);
    await Share.shareXFiles(
      [XFile(path, mimeType: 'text/csv')],
      subject: 'Attendance Report',
      text: 'Here is the attendance report.',
    );
  }

  static Future<String?> saveAttendanceToDevice(List<AttendanceRecord> records) async {
    final exportPath = await exportAttendanceToCsv(records);
    final fileName = p.basename(exportPath);
    final String? outputPath = await FilePicker.platform.saveFile(
      dialogTitle: 'Save Attendance Report',
      fileName: fileName,
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );
    if (outputPath == null) return null;
    final fileBytes = await File(exportPath).readAsBytes();
    await File(outputPath).writeAsBytes(fileBytes);
    return outputPath;
  }

  // ==================== TIMETABLE CSV EXPORT ====================

  static Future<String> exportTimetableToCsv(List<TimetableEntry> entries) async {
    final rows = <List<String>>[
      TimetableEntry.csvHeaders,
      ...entries.map((e) => e.toCsvRow()),
    ];
    final csvContent = _CsvHelper.encode(rows);
    final dir = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final fileName = 'timetable_export_$timestamp.csv';
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(csvContent, encoding: utf8);
    return file.path;
  }

  static Future<void> exportAndShareTimetable(List<TimetableEntry> entries) async {
    final path = await exportTimetableToCsv(entries);
    await Share.shareXFiles(
      [XFile(path, mimeType: 'text/csv')],
      subject: 'Timetable Export',
      text: 'Here is the timetable export.',
    );
  }

  static Future<String?> saveTimetableToDevice(List<TimetableEntry> entries) async {
    final exportPath = await exportTimetableToCsv(entries);
    final fileName = p.basename(exportPath);
    final String? outputPath = await FilePicker.platform.saveFile(
      dialogTitle: 'Save Timetable',
      fileName: fileName,
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );
    if (outputPath == null) return null;
    final fileBytes = await File(exportPath).readAsBytes();
    await File(outputPath).writeAsBytes(fileBytes);
    return outputPath;
  }

  // ==================== PDF PLACEHOLDER EXPORT ====================

  static Future<String> exportAttendanceToPdfPlaceholder(List<AttendanceRecord> records) async {
    return PdfPlaceholderService.generateTextReport(
      title: 'ATTENDANCE REPORT',
      subtitle: 'StudyFlow App',
      headers: AttendanceRecord.csvHeaders,
      rows: records.map((r) => r.toCsvRow()).toList(),
    );
  }

  static Future<String> exportTimetableToPdfPlaceholder(List<TimetableEntry> entries) async {
    return PdfPlaceholderService.generateTextReport(
      title: 'TIMETABLE REPORT',
      subtitle: 'StudyFlow App',
      headers: TimetableEntry.csvHeaders,
      rows: entries.map((e) => e.toCsvRow()).toList(),
    );
  }

  static Future<void> shareAttendancePdfPlaceholder(List<AttendanceRecord> records) async {
    final path = await exportAttendanceToPdfPlaceholder(records);
    await Share.shareXFiles(
      [XFile(path, mimeType: 'text/plain')], // Using text/plain as placeholder
      subject: 'Attendance Report (PDF Placeholder)',
      text: 'Here is the attendance report (text-based PDF placeholder).',
    );
  }

  static Future<void> shareTimetablePdfPlaceholder(List<TimetableEntry> entries) async {
    final path = await exportTimetableToPdfPlaceholder(entries);
    await Share.shareXFiles(
      [XFile(path, mimeType: 'text/plain')], // Using text/plain as placeholder
      subject: 'Timetable Report (PDF Placeholder)',
      text: 'Here is the timetable report (text-based PDF placeholder).',
    );
  }

  // ==================== CSV IMPORT (BULK ENTRY) ====================

  static Future<List<AttendanceRecord>> importAttendanceFromCsv(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File not found: $filePath');
    }
    final contents = await file.readAsString(encoding: utf8);
    if (contents.trim().isEmpty) {
      throw Exception('File is empty');
    }
    final rows = _CsvHelper.decode(contents);
    if (rows.isEmpty) {
      throw Exception('CSV file has no data rows');
    }

    var startIndex = 0;
    final firstRow = rows.first.map((c) => c.toLowerCase().trim()).toList();
    final expectedHeaders = AttendanceRecord.csvHeaders.map((h) => h.toLowerCase()).toList();
    if (_rowsMatchHeaders(firstRow, expectedHeaders)) {
      startIndex = 1;
    }

    final records = <AttendanceRecord>[];
    final errors = <String>[];

    for (var i = startIndex; i < rows.length; i++) {
      try {
        final record = AttendanceRecord.fromCsvRow(rows[i]);
        records.add(record);
      } catch (e) {
        errors.add('Row ${i + 1}: $e');
      }
    }

    if (errors.isNotEmpty && records.isEmpty) {
      throw FormatException('All rows failed to parse:\n${errors.take(5).join('\n')}');
    }

    return records;
  }

  static Future<List<TimetableEntry>> importTimetableFromCsv(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      throw Exception('File not found: $filePath');
    }
    final contents = await file.readAsString(encoding: utf8);
    if (contents.trim().isEmpty) {
      throw Exception('File is empty');
    }
    final rows = _CsvHelper.decode(contents);
    if (rows.isEmpty) {
      throw Exception('CSV file has no data rows');
    }

    var startIndex = 0;
    final firstRow = rows.first.map((c) => c.toLowerCase().trim()).toList();
    final expectedHeaders = TimetableEntry.csvHeaders.map((h) => h.toLowerCase()).toList();
    if (_rowsMatchHeaders(firstRow, expectedHeaders)) {
      startIndex = 1;
    }

    final entries = <TimetableEntry>[];
    final errors = <String>[];

    for (var i = startIndex; i < rows.length; i++) {
      try {
        final entry = TimetableEntry.fromCsvRow(rows[i]);
        entries.add(entry);
      } catch (e) {
        errors.add('Row ${i + 1}: $e');
      }
    }

    if (errors.isNotEmpty && entries.isEmpty) {
      throw FormatException('All rows failed to parse:\n${errors.take(5).join('\n')}');
    }

    return entries;
  }

  static Future<List<AttendanceRecord>> importAttendanceFromPicker() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.isEmpty) {
      throw Exception('No file selected');
    }
    final path = result.files.single.path;
    if (path == null) {
      throw Exception('Could not access file path');
    }
    return importAttendanceFromCsv(path);
  }

  static Future<List<TimetableEntry>> importTimetableFromPicker() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
      allowMultiple: false,
      withData: false,
    );
    if (result == null || result.files.isEmpty) {
      throw Exception('No file selected');
    }
    final path = result.files.single.path;
    if (path == null) {
      throw Exception('Could not access file path');
    }
    return importTimetableFromCsv(path);
  }

  static bool _rowsMatchHeaders(List<String> row, List<String> headers) {
    if (row.length < headers.length) return false;
    for (var i = 0; i < headers.length; i++) {
      if (row[i] != headers[i]) return false;
    }
    return true;
  }

  // ==================== MONTHLY AUTO-BACKUP ====================

  static Future<ExportResult> triggerAutoBackup() async {
    return exportAllData();
  }

  static Future<void> initializeMonthlyAutoBackup() async {
    BackupWorkManager.initialize();
    await BackupWorkManager.registerMonthlyBackup();
  }

  static Future<void> cancelMonthlyAutoBackup() async {
    await BackupWorkManager.cancelMonthlyBackup();
  }
}
